name: building

on:
  push:
    branches:
      - actions

jobs:
  test:
    name: check env
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: check env
        run: |
          cat /etc/*release*
          yum -y install make
          # yum -y update && yum -y upgrade && yum install -y wget

          # - name: install golang
          # run: |
          # wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
          # rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
          # export PATH=$PATH:/usr/local/go/bin
          # go version

      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v1
        with:
          go-version: ~1.17

      - name: check go version
        run: |
          go version
          make build
          ls -al 
