name: building

on:
  push:
    branches:
      - actions

jobs:
  test:
    name: check env
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - name: check env
        run: |
          pwd
          cat /etc/*release*

      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v1
        with:
          go-version: ~1.17


